-- Customers Table
CREATE TABLE Customers (
    Customer_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Contact_Number VARCHAR2(20),
    Email VARCHAR2(100)
);

-- Employees Table
CREATE TABLE Employees (
    Employee_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Role VARCHAR2(50),
    Contact_Number VARCHAR2(20)
);

-- Cars Inventory Table
CREATE TABLE Cars_Inventory (
    Vehicle_ID NUMBER PRIMARY KEY,
    Make VARCHAR2(50),
    Model VARCHAR2(50),
    Price NUMBER(10, 2),
    Availability VARCHAR2(20)  -- e.g. 'Available', 'Sold'
);

-- Transactions Table
CREATE TABLE Transactions (
    Transaction_ID NUMBER PRIMARY KEY,
    Customer_ID NUMBER,
    Vehicle_ID NUMBER,
    Sale_Date DATE,
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID),
    FOREIGN KEY (Vehicle_ID) REFERENCES Cars_Inventory(Vehicle_ID)
);

-- Audit Log Table
CREATE TABLE Audit_Log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Table_Name VARCHAR2(100),
    Operation VARCHAR2(10),         -- e.g. 'INSERT', 'UPDATE', 'DELETE'
    Changed_By VARCHAR2(100),       -- Username or Employee_ID
    Change_Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Old_Value CLOB,
    New_Value CLOB
);
